name: Default
on: [push]

jobs:
  lint-test:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ankane/setup-mongodb@v1
      - name: run test script
        run: npx eslint .
